void draw_epoch(){
  TString histoFileName = "data3/histo_epoch.root";
  TFile* histoFile = TFile::Open(histoFileName);
  TH1D* hStsTimeFull     = (TH1D*) histoFile->Get("hStsTimeFull");
  TH1D* hStsTimeCentral  = (TH1D*) histoFile->Get("hStsTimeCentral");
  TH1D* hMuchTimeFull    = (TH1D*) histoFile->Get("hMuchTimeFull");
  TH1D* hMuchTimeCentral = (TH1D*) histoFile->Get("hMuchTimeCentral");
  hStsTimeFull->SetStats(0);
  hStsTimeCentral->SetStats(0);
  hStsTimeFull->GetYaxis()->SetTitleOffset(0.8);
  hStsTimeCentral->GetYaxis()->SetTitleOffset(0.8);
  hMuchTimeFull->SetStats(0);
  hMuchTimeCentral->SetStats(0);
  hMuchTimeFull->GetYaxis()->SetTitleOffset(0.8);
  hMuchTimeCentral->GetYaxis()->SetTitleOffset(0.8);
  TCanvas* c1 = new TCanvas("c1","Sts time",1200,900);
  c1->Divide(1,2);
  c1->cd(1);
  gPad->SetRightMargin(0.02);
  gPad->SetLeftMargin(0.06);
  gPad->SetTopMargin(0.01);
  gPad->SetLogy();
  hStsTimeFull->Draw();
  c1->cd(2);
  gPad->SetRightMargin(0.02);
  gPad->SetLeftMargin(0.06);
  gPad->SetTopMargin(0.01);
  gPad->SetLogy();
  hStsTimeCentral->Draw();
  TCanvas* c2 = new TCanvas("c2","Much time",1200,900);
  c2->Divide(1,2);
  c2->cd(1);
  gPad->SetRightMargin(0.02);
  gPad->SetLeftMargin(0.06);
  gPad->SetTopMargin(0.01);
  gPad->SetLogy();
  hMuchTimeFull->Draw();
  c2->cd(2);
  gPad->SetRightMargin(0.02);
  gPad->SetLeftMargin(0.06);
  gPad->SetTopMargin(0.01);
  gPad->SetLogy();
  hMuchTimeCentral->Draw();
  c2->cd();
}
