void runEpochTestDraw(){
  TString histoFileName = "data/histo_epoch.1MHz.root";
  TFile* histoFile = TFile::Open(histoFileName);
  TH1D* hStsTimeFull     = (TH1D*) histoFile->Get("hStsTimeFull");
  TH1D* hStsTimeCentral  = (TH1D*) histoFile->Get("hStsTimeCentral");
  TH1D* hMuchTimeFull    = (TH1D*) histoFile->Get("hMuchTimeFull");
  TH1D* hMuchTimeCentral = (TH1D*) histoFile->Get("hMuchTimeCentral");
  hStsTimeFull->SetStats(0);
  hStsTimeCentral->SetStats(0);
  hStsTimeFull->GetYaxis()->SetTitleOffset(0.8);
  hStsTimeCentral->GetYaxis()->SetTitleOffset(0.8);
  hMuchTimeFull->SetStats(0);
  hMuchTimeCentral->SetStats(0);
  hMuchTimeFull->SetLineColor(kRed);
  hMuchTimeCentral->SetLineColor(kRed);
  hMuchTimeFull->GetYaxis()->SetTitleOffset(0.8);
  hMuchTimeCentral->GetYaxis()->SetTitleOffset(0.8);
  TCanvas* c1 = new TCanvas("c1","Sts time",1200,900);
  c1->Divide(1,2);
  c1->cd(1);
  gPad->SetRightMargin(0.02);
  gPad->SetLeftMargin(0.06);
  gPad->SetTopMargin(0.10);
  gPad->SetLogy();
  hStsTimeFull->SetTitle("First STS layer. All points.");
  hStsTimeFull->DrawClone();
  c1->cd(2);
  gPad->SetRightMargin(0.02);
  gPad->SetLeftMargin(0.06);
  gPad->SetTopMargin(0.10);
  gPad->SetLogy();
  hStsTimeCentral->SetTitle("First STS layer. Central region.");
  hStsTimeCentral->DrawClone();
  TCanvas* c2 = new TCanvas("c2","Much time",1200,900);
  c2->Divide(1,2);
  c2->cd(1);
  gPad->SetRightMargin(0.02);
  gPad->SetLeftMargin(0.06);
  gPad->SetTopMargin(0.10);
  gPad->SetLogy();
  hMuchTimeFull->SetTitle("First MUCH layer. All points.");
  hMuchTimeFull->DrawClone();
  c2->cd(2);
  gPad->SetRightMargin(0.02);
  gPad->SetLeftMargin(0.06);
  gPad->SetTopMargin(0.10);
  gPad->SetLogy();
  hMuchTimeCentral->SetTitle("First MUCH layer. Central region.");
  hMuchTimeCentral->DrawClone();
  TCanvas* c3 = new TCanvas("c3","STS+MUCH time",1200,900);
  c3->Divide(1,2);
  c3->cd(1);
  gPad->SetRightMargin(0.02);
  gPad->SetLeftMargin(0.06);
  gPad->SetTopMargin(0.10);
  gPad->SetLogy();
  
  hStsTimeFull->SetTitle("First STS layer + First MUCH layer. All points.");
  hStsTimeFull->DrawClone();
  hMuchTimeFull->DrawClone("same");
  c3->cd(2);
  gPad->SetRightMargin(0.02);
  gPad->SetLeftMargin(0.06);
  gPad->SetTopMargin(0.10);
  gPad->SetLogy();
  hStsTimeCentral->SetTitle("First STS layer + First MUCH layer. Central region.");
  hStsTimeCentral->DrawClone();
  hMuchTimeCentral->DrawClone("same");
  c3->cd();
}
