// --------------------------------------------------------------------------
// -----             Header for the CbmTrdHitProducerSmearing          ------
// -----          Partially Created by M. Kalisky                      ------
// -----           Last update 21.03.05 by M. Kalisky                  ------
// -----           Renamed from CbmTrdHitProducer 04.043.09 F. Uhlig   ------
// --------------------------------------------------------------------------


/**
 **   !!! WARNING  !!!
 **   temporary solution  ONLY for old CVS release (before implementation of the
 **   parameters by Mohammad and Dennis)
 **
 **   compatibility with the new release is not granted.
 **   This hit producer works only with geometry versions for 9 and 12
 **   TRD layers.
 **
 **   For any more detailed studies including the TRD I strongly advice
 **   to use the new release (should be provided before end of May)
 **
 **   Any futere developements will be implemented only for the new release
 **
 *@   m.kalisky@gsi.de
 **/

/* Generated by Together */

#ifndef CBMTRDHITPRODUCERSMEARING_H
#define CBMTRDHITPRODUCERSMEARING_H


#include "FairTask.h"

#include "TVector3.h"

class TClonesArray;
class FairBaseParSet;
class CbmGeoTrdPar;
class CbmTrdHit;
class CbmTrdRadiator;


    class CbmTrdHitProducerSmearing : public FairTask {
public:

    

    /** Default constructor **/
    CbmTrdHitProducerSmearing();

    /** Standard constructor **/
    CbmTrdHitProducerSmearing(const char *name, const char *title="CBM Task", CbmTrdRadiator *radiator=NULL);

    /** Destructor **/
    virtual ~CbmTrdHitProducerSmearing();

    /** Initialisation **/
    virtual InitStatus ReInit();
    virtual InitStatus Init();
    virtual void SetParContainers();

    /** Executed task **/
    virtual void Exec(Option_t * option);

    /** Finish task **/
    virtual void Finish();

    //TRefArray *GetRef(){return fRef;}
    void AddHit(TVector3 &posHit, TVector3 &posHitErr,
		Int_t TrackID, Int_t PlaneID, Int_t ref, Double_t ELoss,
		Double_t ELossTR, Double_t ELossdEdX);
    void SmearingXY( Double_t dx , Double_t dy ) { fDx = dx; fDy=dy ;}
    void SmearingX(Double_t dx) {fDx = dx;}
    void SmearingY(Double_t dy) {fDy = dy;}
    void Register();
    void SetNlayer(Int_t a) ;
    void SetEfficency(Float_t eff) {fEfficency=eff;}
    void SetSigmaX(Double_t sigma[]) ;
    void SetSigmaY(Double_t s1[], Double_t s2[], Double_t s3[]);

    Double_t GetSigmaX (Int_t stack);
    Float_t GetEfficency () { return fEfficency;}
    Double_t GetSigmaY (Double_t teta, Int_t stack );

private:

    TClonesArray *fTrdPoints; //! TRD MC points
    TClonesArray *fHitCollection; //! TRD hits
    TClonesArray *fListStack;         //Tracks

    Double_t fDx;               //!
    Double_t fDy;               //!
    Double_t fSigmaX[3];        //!
    Double_t fSigmaY[3] [7];    //!
    Int_t    fTrdPerStation;    //!
    Int_t    fNlayer;           //!
    TString  fVersion;          //!
    Int_t    fNHits;            //!
    Float_t  fEfficency;        //! Hit finding efficency (0-100%)

    CbmTrdRadiator*  fRadiator; //!
    CbmGeoTrdPar*    fGeoPar;   //!
    FairBaseParSet*    fBasePar; //!

    // positions of the active volume for given copyes of the chambers
    // temporary solution

    Float_t ftrdU1[8];      //!
    Float_t ftrdU2[8];      //!
    Float_t ftrdU3[8];      //!
    Float_t ftrdR1[8];      //!
    Float_t ftrdR2[8];      //!
    Float_t ftrdR3[8];      //!

    ClassDef(CbmTrdHitProducerSmearing,1) //CBMTRDHitProducer

};
#endif //CBMTRDHITPRODUCERSMEARING_H
