/* Generated by Together */

#include "CbmCave.h"

#include "CbmGeoCave.h"

#include "CbmGeoInterface.h"
#include "CbmGeoRootBuilder.h"
#include "CbmRuntimeDb.h"
#include "CbmGeoPassivePar.h"
#include "CbmGeoVolume.h"
#include "CbmGeoNode.h"
#include "CbmRun.h"
#include "CbmMCApplication.h"
#include "CbmVolume.h"
#include "CbmVolumeList.h"
#include "CbmGeoLoader.h"

#include "TGeoMCGeometry.h"
#include "TGeoManager.h"
#include "TGeoVolume.h"
#include "TGeoMedium.h"
#include "TObjArray.h"

ClassImp(CbmCave)
void CbmCave::ConstructGeometry()
{
	CbmGeoLoader *loader=CbmGeoLoader::Instance();
	CbmGeoInterface *GeoInterface =loader->getGeoInterface();
	CbmGeoCave *MGeo=new CbmGeoCave();
	MGeo->setGeomFile(GetGeometryFileName());
	GeoInterface->addGeoModule(MGeo);
	Bool_t rc = GeoInterface->readSet(MGeo);
	if ( rc ) MGeo->create(loader->getGeoBuilder());

        TList* volList = MGeo->getListOfVolumes();
        // store geo parameter
        CbmRun *fRun = CbmRun::Instance();
        CbmRuntimeDb *rtdb= CbmRun::Instance()->GetRuntimeDb();
        CbmGeoPassivePar* par=(CbmGeoPassivePar*)(rtdb->getContainer("CbmGeoPassivePar"));
        TObjArray *fSensNodes = par->GetGeoSensitiveNodes();
        TObjArray *fPassNodes = par->GetGeoPassiveNodes();

        TListIter iter(volList);
        CbmGeoNode* node   = NULL;
        CbmGeoVolume *aVol=NULL;

        while( (node = (CbmGeoNode*)iter.Next()) ) {
            aVol = dynamic_cast<CbmGeoVolume*> ( node );
            if ( node->isSensitive()  ) {
                fSensNodes->AddLast( aVol );
            }else{
                fPassNodes->AddLast( aVol );
            }
        }
        par->setChanged();
        par->setInputVersion(fRun->GetRunId(),1);

}
CbmCave::CbmCave(){
}

CbmCave::~CbmCave()
{

}
CbmCave::CbmCave(const char * name,  const char *Title)
  : CbmModule(name ,Title)
{
    world[0] = 0;
    world[1] = 0;
    world[2] = 0;
}
