/* Generated by Together */
#include "CbmTarget.h"

#include "CbmGeoTarget.h"
#include "CbmGeoPassivePar.h"

#include "CbmGeoLoader.h"
#include "CbmGeoInterface.h"
#include "CbmGeoRootBuilder.h"
#include "CbmRuntimeDb.h"
#include "CbmRun.h"
#include "CbmGeoVolume.h"
#include "CbmGeoNode.h"

#include "TObjArray.h"

CbmTarget::~CbmTarget()
{
}
CbmTarget::CbmTarget()
{
}

CbmTarget::CbmTarget(const char * name,  const char * title)
  : CbmModule(name ,title)
{
}
void CbmTarget::ConstructGeometry()
{
	CbmGeoLoader *loader=CbmGeoLoader::Instance();
	CbmGeoInterface *GeoInterface =loader->getGeoInterface();
	CbmGeoTarget *MGeo=new CbmGeoTarget();
	MGeo->setGeomFile(GetGeometryFileName());
	GeoInterface->addGeoModule(MGeo);
	Bool_t rc = GeoInterface->readSet(MGeo);
	if ( rc ) MGeo->create(loader->getGeoBuilder());

        TList* volList = MGeo->getListOfVolumes();
        // store geo parameter
        CbmRun *fRun = CbmRun::Instance();
        CbmRuntimeDb *rtdb= CbmRun::Instance()->GetRuntimeDb();
        CbmGeoPassivePar* par=(CbmGeoPassivePar*)(rtdb->getContainer("CbmGeoPassivePar"));
        TObjArray *fSensNodes = par->GetGeoSensitiveNodes();
        TObjArray *fPassNodes = par->GetGeoPassiveNodes();

        TListIter iter(volList);
        CbmGeoNode* node   = NULL;
        CbmGeoVolume *aVol=NULL;

        while( (node = (CbmGeoNode*)iter.Next()) ) {
            aVol = dynamic_cast<CbmGeoVolume*> ( node );
            if ( node->isSensitive()  ) {
                fSensNodes->AddLast( aVol );
            }else{
                fPassNodes->AddLast( aVol );
            }
        }
	ProcessNodes( volList );
        par->setChanged();
        par->setInputVersion(fRun->GetRunId(),1);

}
ClassImp(CbmTarget)



