//
//   TRD pad layout for geometry v14b
//
// automatically generated by Create_TRD_Geometry_v14b_3e.C
// created 20140610
//

#ifndef CBMTRDPADS_H
#define CBMTRDPADS_H

Int_t fst1_sect_count = 3;
// array of pad geometries in the TRD (trd1mod[1-8])
// 8 modules  // 3 sectors  // 4 values 
Float_t fst1_pad_type[8][3][4] =        
			 		 
// module type 1
// number of pads:  80 x 36 = 2880
// pad size sector 1:  0.68 cm x  1.50 cm =  1.01 cm2
// pad size sector 0:  0.68 cm x  1.50 cm =  1.01 cm2
  { { { 54.0, 18.00, 54.0/ 80,  1.50 },
      { 54.0, 18.00, 54.0/ 80,  1.50 },
      { 54.0, 18.00, 54.0/ 80,  1.50 } },

// module type 2
// number of pads:  80 x 20 = 1600
// pad size sector 1:  0.68 cm x  2.50 cm =  1.69 cm2
// pad size sector 0:  0.68 cm x  2.75 cm =  1.86 cm2
    { { 54.0, 22.00, 54.0/ 80,  2.75 },
      { 54.0, 10.00, 54.0/ 80,  2.50 },
      { 54.0, 22.00, 54.0/ 80,  2.75 } },

// module type 3
// number of pads:  80 x 12 =  960
// pad size sector 1:  0.68 cm x  4.50 cm =  3.04 cm2
// pad size sector 0:  0.68 cm x  4.50 cm =  3.04 cm2
    { { 54.0,  4.50, 54.0/ 80,  4.50 },
      { 54.0, 45.00, 54.0/ 80,  4.50 },
      { 54.0,  4.50, 54.0/ 80,  4.50 } },

// module type 4
// number of pads:  80 x  8 =  640
// pad size sector 1:  0.68 cm x  6.75 cm =  4.56 cm2
// pad size sector 0:  0.68 cm x  6.75 cm =  4.56 cm2
    { { 54.0, 13.50, 54.0/ 80,  6.75 },
      { 54.0, 27.00, 54.0/ 80,  6.75 },
      { 54.0, 13.50, 54.0/ 80,  6.75 } },

//---

// module type 5
// number of pads: 128 x 24 = 3072
// pad size sector 1:  0.71 cm x  4.00 cm =  2.84 cm2
// pad size sector 0:  0.71 cm x  3.75 cm =  2.67 cm2
    { { 91.0, 37.50, 91.0/128,  3.75 },
      { 91.0, 16.00, 91.0/128,  4.00 },
      { 91.0, 37.50, 91.0/128,  3.75 } },

// module type 6
// number of pads: 128 x 12 = 1536
// pad size sector 1:  0.71 cm x  7.75 cm =  5.51 cm2
// pad size sector 0:  0.71 cm x  7.50 cm =  5.33 cm2
    { { 91.0, 30.00, 91.0/128,  7.50 },
      { 91.0, 31.00, 91.0/128,  7.75 },
      { 91.0, 30.00, 91.0/128,  7.50 } },

// module type 7
// number of pads: 128 x  8 = 1024
// pad size sector 1:  0.71 cm x 11.50 cm =  8.18 cm2
// pad size sector 0:  0.71 cm x 11.25 cm =  8.00 cm2
    { { 91.0, 22.50, 91.0/128, 11.25 },
      { 91.0, 46.00, 91.0/128, 11.50 },
      { 91.0, 22.50, 91.0/128, 11.25 } },

// module type 8
// number of pads: 128 x  6 =  768
// pad size sector 1:  0.71 cm x 15.50 cm = 11.02 cm2
// pad size sector 0:  0.71 cm x 15.00 cm = 10.66 cm2
    { { 91.0, 30.00, 91.0/128, 15.00 },
      { 91.0, 31.00, 91.0/128, 15.50 },
      { 91.0, 30.00, 91.0/128, 15.00 } } };

#endif
