#ifndef LXSETTINGS_INCLUDED
#define LXSETTINGS_INCLUDED

#define LXPI 3.141592653589793238462643383279

#define LXLAYERS 3
#define LXSTATIONS 6
#define LXMIDDLE 1
#define LXFIRSTSTATION 0

//#define MAKE_HISTOS

#ifdef MAKE_HISTOS
//#define MAKE_ANGLE_HISTOS
//#define MAKE_BRAKE_ANGLE_HISTOS
//#define MAKE_DISPERSE_HISTOS
//#define MAKE_MU_PLUS_MU_MINUS_HISTOS
//#define MAKE_DIFF_FIT_HISTOS
#define MAKE_DIFF_FIRST_HISTOS
//#define MAKE_FIT_COEFFS_HISTOS
//#define MAKE_LAST_STS_NEAREST_Y

#endif//MAKE_HISTOS

#define MAKE_STS_MC_RESEARCHES
#define MAKE_EFF_CALC
//#define CALC_MUCH_DETECTORS_EFF
//#define CALC_LINK_WITH_STS_EFF

#endif//LXSETTINGS_INCLUDED
