include $(ROCSYS)/config/Makefile.arch

INCLUDES = $(ROCSYS)/roclib

CXXOPT += $(INCLUDES:%=-I%)

ROC_FASTRULES = clean

ROC_DEPENDENCIES =

ROC_LIBDIR = $(ROCSYS)/lib
ROC_BINDIR = $(ROCSYS)/bin

LDFLAGS       = -b 

LD            = g++
CXX           = g++
