include $(ROCSYS)/config/Makefile.arch

INCLUDES = $(ROCSYS)/include

CXXOPT += $(INCLUDES:%=-I%)

ROC_FASTRULES = clean

ROC_DEPENDENCIES =

LDFLAGS       = -b 

LD            = g++
CXX           = g++
